### ISSUE TITLE
Amazing tool, but I can't get access to some of the HTTPS traffic 

### ISSUE THREAD

**Issue by a66at** [evilpenguin/NetworkSniffer#1]
**Expected Behavior**
Interception of requests from the Lyft app (https://apps.apple.com/us/app/lyft/id529379082) to the API server: https://api.lyft.com/
**Current Behavior**
Only one event in the console.app:
  _+[NetworkSniffer] Starting_ 
**Context (Environment)**
iOS 13.3, iPhone SE (uncover JB)

**Comment by evilpenguin** [comment]
Lyft might be blocking my method, as its common. Does it work on other apps?

**Comment by a66at** [comment]
yes, works perfect for the apps, where sslunpinning works as well. I was trying to use your tool to get access to the traffic where this is hard. Thanks anyway!

**Comment by hmaks36** [comment]
For me, not working with SSL Pinning ( Alamofire / NSURLSession ), Work with WKWebView. Apps are my own so no custom method blocking. good job !

**Comment by evilpenguin** [comment]
@hmaks36 So you have SSL pinning and this no longer works?
