### ISSUE TITLE
No deb file?

### ISSUE THREAD

**Issue by patelt3** [evilpenguin/NetworkSniffer#3]
There's no "package" folder or deb file in the repo. Did those get deleted?

**Comment by evilpenguin** [comment]
Crap! I must have deleted it from the commit. I'll fix this later tonight and push it. 

You can always run "make package" and it /should/ just compile + package. Just make sure you have theos setup.

**Comment by duraki** [comment]
Just checkout pre-[362fb176af3cd5bcc4f5eff9517ea9f618c7a4cb](https://github.com/evilpenguin/NetworkSniffer/commit/362fb176af3cd5bcc4f5eff9517ea9f618c7a4cb) locally, it has latest `deb` prior deletion (which obviously may not be comparable to master). 

~ edit: [dirty download](https://github.com/evilpenguin/NetworkSniffer/raw/4e0ae672b4b5d57d25415bc47b26f38678251f85/packages/com.evilpenguin.networksniffer_0.1.0-6%2Bdebug_iphoneos-arm.deb)

**Comment by evilpenguin** [comment]
pushed.
